### ISSUE TITLE
Prusti internal error using hash get

### ISSUE THREAD

**Issue by ghost** [viperproject/prusti-dev#1039]
Sorry if this is already mentioned in the docs or the issues, I tried to look for it without luck.

When I try to run `prusti-rustc` to this simple program:

```
fn main(){
    let i: usize = 0;

    let mut hash: HashMap<usize, usize> = HashMap::new();

    let a = hash.get(&i).unwrap()-1;
}
```

I receive 
```

error: [Prusti internal error] Prusti encountered an unexpected internal error
   --> src/lib.rs:191:13
    |
191 |     let a = hash.get(&i).unwrap()-1;
    |             ^^^^^^^^^^^^
    |
    = note: We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new
    = note: Details: tried to encode a projection that accesses the field 0 of a variant without first downcasting its enumeration std::option::Option<&usize>

Verification failed
```

Is it because this object is not supported? Do I have a workaround to use hashmaps?

**Comment by JonasAlaif** [comment]
This error will be fixed by https://github.com/viperproject/prusti-dev/pull/1031. When looking for related issues I'd recommend using some of the error text to search, e.g. if I use `tried to encode a projection that accesses the field 0 of a variant without first downcasting its enumeration` as a search term in the GitHub issues page I get exactly the two identical issues and from there can find the linked PR.
Regarding your code, even though the PR would fix this crash, the code is still not supported by Prusti; think about the signature of `get` or the monomorphised `unwrap`:
```rust
fn get(&self, k: &Q) -> Option<&V> { ... }
fn unwrap(x: Option<&usize>) -> &usize { ... }
```
Neither is supported since they have a referenced typed field; `Option<&_>`
(If you really need them, then define a `#[trusted]` wrapper function, see https://github.com/viperproject/prusti-dev/issues/1029)
