### ISSUE TITLE
Cache dependent unregistered verification error

### ISSUE THREAD

**Issue by dewert99** [viperproject/prusti-dev#1083]
While verifing the program:
```rust
use prusti_contracts::*;
fn main() {
    test(2);
    assert!(false);
}

#[requires(x == 2)]
#[ensures(x == 5)]
fn test(mut x: u32) {
    assert!(x == 2);
    x = 5;
    assert!(x == 5);
}
```
I got this error:
```
error: [Prusti internal error] Prusti encountered an unexpected internal error                                                                                                         
  --> src\lib.rs:12:5
   |
12 |     assert!(x == 5);
   |     ^^^^^^^^^^^^^^^
   |
   = help: This could be caused by too small assertion timeout. Try increasing it by setting the configuration parameter ASSERT_TIMEOUT to a larger value.
   = note: We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new
   = note: Details: unregistered verification error: [assert.failed:assertion.false; 135] Assert might fail. Assertion old[pre]((unfolding acc(u32(_1), write) in _1.val_int)) == 5 might not hold. (@37.11)
   = note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)
```
I noticed that errors would go away if I replaced all 5's or 2's with another number.  I eventually realized the error also went away if I deleted `target/verify/cache.bin` which I have attached as [cache.zip](https://github.com/viperproject/prusti-dev/files/9075569/cache.zip)

**Comment by JonasAlaif** [comment]
Yep, this is due to a caching issue which I need to resolve, sorry. Both #971 and #1045 are different fixes for this, I just need to pick one and merge it. It only comes up if you use `cargo-prusti` (since only that uses caching atm) and only for verification failures (after reordering functions).
(It is a duplicate of #940 but I can't expect you to find that after all of the pain you must've gone through to link this to the `target/verify/cache.bin` file; again, sorry)
