### ISSUE TITLE
Unsoundness in Selection Sort

### ISSUE THREAD

**Issue by vakaras** [viperproject/prusti-dev#115]
The following [loop invariant](https://github.com/viperproject/prusti-dev/blob/f6239d1ddac50c0ada0d73421f771f33afbe1aa7/prusti/tests/verify_overflow/pass/rosetta/Selection_sort.rs#L83) should not hold because we do not have a guarantee that the array is not empty. However, Prusti somehow manages to prove it.

**Comment by fpoli** [comment]
It's not a bug. Since mid-June the loop invariant is an invariant of the loop body (just before the first statement), and not of the loop head. If the array is empty the loop body is not reached, thus the loop invariant is not enforced. The [tutorial](https://github.com/viperproject/prusti-dev/wiki/tutorial#loop-invariants) should have description of this.

**Comment by vakaras** [comment]
To make the new semantics clearer, I have renamed `invariant!` to `body_invariant!` (https://github.com/viperproject/prusti-dev/pull/129).

**Comment by fpoli** [comment]
> To make the new semantics clearer, I have renamed `invariant!` to `body_invariant!` (#129).

I updated the [tutorial](https://github.com/viperproject/prusti-dev/wiki/Tutorial). Let's remember to do that when we change the syntax/semantics.
