### ISSUE TITLE
Prusti latest dev version throws error on unreachable statements

### ISSUE THREAD

**Issue by Ramla-I** [viperproject/prusti-dev#1165]
I'm using the latest dev branch with prusti assistant (Prusti version: commit 19c1732), and code that previously compiled with the latest release branch no longer does. There are two issues:

1. - unless I include `prusti-contracts = { git = "https://github.com/viperproject/prusti-dev.git" }` in the Cargo file, prusti cannot compile the code with errors such as "unresolved import `prusti_contracts`"
2. - unreachable!() statements that cannot be reached due to a precondition still cause a prusti error "statement might panic"

These 2 issues occur in all my code I've tried to re-verify with the latest branch. As I test, I went back and tried to verify the code in the user guide [here](https://rust-unofficial.github.io/too-many-lists/first-final.html), and the same error occurs. The most simplest is a function for Option that fails to verify:

```
    #[pure]
    #[requires(self.is_some())]
    pub fn peek(&self) -> i32 {
        match self {
            TrustedOption::Some(val) => *val,
            TrustedOption::None => unreachable!(),
        }
    }
```

**Comment by fpoli** [comment]
Thanks for reporting this. We are working on improving `prusti-contracts` dependencies, but they are not stable yet. For example, until [a few days ago](https://github.com/viperproject/prusti-dev/pull/1146) it was necessary to manually add the `features = ["prusti"]` flag to the dependency in order to run Prusti, which leads to what you described. However, that should no longer be necessary. Could you try again with the latest master version?

**Comment by JonasAlaif** [comment]
Notably, you can now use `prusti-contracts = "^0.1"` in your `Cargo.toml` instead. (see https://crates.io/crates/prusti-contracts)

**Comment by fpoli** [comment]
Closing. Let us know if there are still issues with this.

**Comment by Ramla-I** [comment]
Both of these issue are resolved now. Thanks!
