### ISSUE TITLE
Attribute and configuration flag to opt-in verification

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-dev#1187]
Currently, Prusti tries to verify all functions that are *not* marked with `#[trusted]`. In large codebases the opposite would make more sense: only verify the functions that *are* marked with `#[verified]`. This way, users can gradually opt-in and verify more and more functions without getting scary "unsupported feature" errors on code that is not meant to be verified.

**Comment by JonasAlaif** [comment]
This way we could support all `test-crates` wooo!

**Comment by fpoli** [comment]
Well, I would not enable this new configuration flag in `test-crates`. :smile:

With this configuration flag enabled, we can also change the default precondition of unverified functions to be `false`, as it should be (as in https://github.com/viperproject/prusti-dev/issues/910).

**Comment by Pointerbender** [comment]
Hi guys! Question about this GH issue: is a `#[verified]` attribute currently already in the works? The reason I'm asking is because I find myself exactly in the situation described in the OP :D I also tried the `allow_unreachable_unsupported_code` and `skip_unsupported_features` configuration settings, but with mixed results:

* Setting `allow_unreachable_unsupported_code = true` seems to result in an ICE on this particular code base (which is to be expected, I think, it has all kinds of unsupported features in there, such as Generic Associated Types, Thread Local Storage, etc.).
* Setting `skip_unsupported_features` to `true` works as advertised, but I still get a lot of warnings and errors for methods which I'm not ready to verify yet, which makes it very difficult to target a specific method or module of the code.

**Comment by fpoli** [comment]
Hi! We didn't work on this, but I think it's relatively easy to add:
- [ ] Add a `PRUSTI_OPT_IN_VERIFICATION` flag (dafault `false`) to `prusti-utils/src/config.rs`.
    - @viperproject/prusti-dev is the name of the flag good for you?
- [ ] Describe the new flag in `docs/dev-guide/src/config/flags.md`
- [ ] When the flag is enabled, consider trusted anything that does *not* have `#[verified]`.
    - I think this is the only place to change: https://github.com/viperproject/prusti-dev/blob/0edc61af8f81ff9976e215ebbacf5450e1799e00/prusti-interface/src/specs/mod.rs#L367
- [ ] Add a test to `prusti-tests/tests/verify_overflow/fail` and to `.../pass`.
    - The flag can be set with the header `// compile-flags: -Popt_in_verification=true`
