### ISSUE TITLE
Panic when analyzing `geo-types` crate

### ISSUE THREAD

**Issue by frewsxcv** [viperproject/prusti-dev#1244]
https://github.com/georust/geo/tree/main/geo-types

Output: https://gist.github.com/frewsxcv/69c9921bf9d5d022c146299a885f7e43

**Comment by frewsxcv** [comment]
https://github.com/viperproject/prusti-dev/blob/e6e40f410e3de6dbee3fe24afb2d9f982f749b3b/prusti-viper/src/encoder/procedure_encoder.rs#L6032-L6036

**Comment by JonasAlaif** [comment]
The problem stems from encoding the fn here:
https://github.com/georust/geo/blob/65240e0a7672f0791b86afbba89e14d5fc16df73/geo-types/src/geometry/geometry_collection.rs#L114-L118
Not sure how to get the required info from `rustc` to avoid the above `unwrap` in Prusti, so instead of the `unwrap` we can emit an unsupported error?

**Comment by frewsxcv** [comment]
I opened a PR https://github.com/viperproject/prusti-dev/pull/1246

**Comment by JonasAlaif** [comment]
Awesome, thanks!
