### ISSUE TITLE
Generics in predicates and purity

### ISSUE THREAD

**Issue by Stef-Gijsberts** [viperproject/prusti-dev#1286]
## Example

This works fine, as expected:

```rust
predicate! {
    fn gt(a: i32, b: i32) -> bool {
        a > b
    }
}

fn main() {
    let a: i32 = 5;
    let b: i32 = 3;
    prusti_assert!(gt(a, b));
}
```

Yet, the following fails with `[Prusti: invalid specification] use of impure function "std::cmp::PartialOrd::gt" in pure code is not allowed`. That surprises me as the previous example did work. 

```rust
predicate! {
    fn gt<T: PartialOrd>(a: T, b: T) -> bool {
        a > b
    }
}

fn main() {
    let a: i32 = 5;
    let b: i32 = 3;
    prusti_assert!(gt(a, b));
}
```

## What I actually want to do

The above is a minimal example, derived from what I actually wanted to do. For context, here is what I hoped to be able to write:

```rust
predicate! {
    fn increasing<T: PartialOrd>(s: &[T]) -> bool {
        forall(|i: usize, j: usize|
            (0 <= i && i < j && j < s.len() ==> s[i] < s[j]))
    }
}
```

### Edit: Workaround

I noticed that I can work around the issue by defining a new 'pure' variant of the trait. Is this the right way to do this?

```rust
trait PurePartialOrd {
    #[pure]
    fn lt(&self, rhs: &Self) -> bool;
}

impl PurePartialOrd for i32 {
    #[pure]
    fn lt(&self, rhs: &i32) -> bool {
        *self < *rhs
    }
}

predicate! {
    fn increasing<T: PurePartialOrd>(s: &[T]) -> bool {
        forall(|i: usize, j: usize|
            (0 <= i && i < j && j < s.len() ==> s[i].lt(&s[j])))
    }
```

**Comment by fpoli** [comment]
Thank you for the report.

It is not sound (for Prusti) to assume that every implementation of `PartialOrd::lt` is pure, because types can still implement the method in a way that has side effects (e.g. interior mutability) or non-determinism. So, we have to special-case some types for which that's fine, e.g. `i32`.

The pure trait solution that you wrote looks fine to me, nice! The issue is that Prusti knows hot to compare `i32` types, but not `&i32`. A shorter solution is to mark the implementation of `PartialOrd<i32>::lt` as pure, using `*self < *other` in the postcondition. At some point we'll do this in Prusti itself, so that the `#[extern_spec] impl ... { ... }` is no longer needed.

```rust
use prusti_contracts::*;

#[extern_spec]
impl PartialOrd<i32> for i32{
    #[pure]
    #[ensures(result == (*self < *other))]
    fn lt(&self, other: &i32) -> bool;
}

predicate! {
    fn increasing<T: PartialOrd>(s: &[T]) -> bool {
        forall(|i: usize, j: usize|
            (i < j && j < s.len() ==> s[i] < s[j]))
    }
}

pub fn main() {
    let x = [1, 2, 3];
    prusti_assert!(increasing(&x));
}
```

**Comment by Aurel300** [comment]
Yes, the `Pure` approach is what we will go for in #1249.

**Comment by fpoli** [comment]
The question has been answered.
