### ISSUE TITLE
How to install prusti on mac m2 chip

### ISSUE THREAD

**Issue by kavitalnu** [viperproject/prusti-dev#1373]
Hi , 

I want to install prusti extension on vs code and need detail steps to install prusti and do verification while using rust language in vs code . 

Can you please provide me detail steps as it is failing showing error on vs code when I tried to add extension "Prusti server stopped working. We would appreciate a [bug report](https://github.com/viperproject/prusti-dev/issues/new). See the log (View -> Output -> Prusti Assistant Server) for more details."

Thanks

**Comment by fpoli** [comment]
We currently do not release precompiled binaries for macOS arm64. So, you have to compile Prusti from source on your own and configure the Prusti extension to use the binaries that you compiled. See https://github.com/viperproject/prusti-dev/issues/1193#issuecomment-1312956882 for the step-by-step instructions.

I'll close this issue because it largely overlaps with https://github.com/viperproject/prusti-dev/issues/1193 (and https://github.com/viperproject/prusti-assistant/issues/191). Please comment there if the instructions don't work.
