### ISSUE TITLE
Carbon cannot verify some loops

### ISSUE THREAD

**Issue by mario-bucev** [viperproject/prusti-dev#15]
Hello!
As far as I've understood, `BeginFrame` and `EndFrame` are used in the context of loops, as a way to frame out and frame in currently held permissions. I have noticed that when such a statement is encountered, the effect of framing is applied to the state of Prusti, but not reflected in the emitted code. That is, no `inhale` and `exhale` are emitted.
https://github.com/viperproject/prusti-dev/blob/134f9f54d00cfc36cb5728ce47c1f984490b3265/prusti-viper/src/encoder/foldunfold/mod.rs#L807-L810

I think this would explain why the following program does not verify when using Carbon (Viper file can be found [here](https://gist.github.com/mario-bucev/b7fb55a6b6bb0d7c8981889bb41f30e4)):
```rust
extern crate prusti_contracts;

// ERROR: Unfolding bool(_1) might fail. 
// There might be insufficient permission to access bool(_1). (whileok.vpr@109.3)
fn whileok() {
    let mut ok = true;
    while ok {}
}

fn main() {}
```

In particular, if we look at the following lines of the Viper program:
https://gist.github.com/mario-bucev/b7fb55a6b6bb0d7c8981889bb41f30e4#file-whileok-vpr-L95-L109
we note that `inhale acc(bool(_1), read$())` comes from the loop permission invariant, but the fact that we unfold `bool(_1)` with write is due to the framing in of the permissions (so we get back full permissions, in that case, `write`).

I don't know if this is an intended behavior, so I am creating this issue.

Thanks :)

**Comment by fpoli** [comment]
Thanks for reporting this! Ideally Silicon and Carbon should always agree (both rejecting a method or both accepting it), so the generated Viper program probably uncovered a bug in one of them. I'll report an issue in Viper as soon as I manage to minimize the Viper program.

Looking at the encoding, the `acc(bool(_1), read$())` loop invariant is correct, because `_1` is never modified inside the loop. So, the error is in the generation of the `unfold acc(bool(_1), write)`, which should be `unfold acc(bool(_1), read())`. With this manual fix, both Carbon and Silicon verify the program. My guess is that by entering the loop Prusti incorrectly remembers that there was a `write-rd()` permission before the loop, thus after inhaling `rd()` Prusti believes that it's fine to unfold with `write`.

As you found, the `BeginFrame` and `EndFrame` don't generate `inhale` or `exhale`, and it's correct. It's because Viper automatically computes frames, and in Prusti we need those statements to remember ourselves to do the same when we are about to enter or exit a loop.

**Comment by fpoli** [comment]
There is actually a second bug: `// [mir] _2 = _1` is encoded in the block `bb1 --> bb3` instead of in the block `bb1`. Weird.

**Comment by fpoli** [comment]
Actually, I was looking at the wrong block. The encoding of Prusti is correct, and the bug seems to be in Carbon only.

**Comment by fpoli** [comment]
I opened this issue: https://github.com/viperproject/carbon/issues/352

**Comment by mario-bucev** [comment]
Ok, thank you for the investigation! Indeed, I wasn't sure whether the verifiers computed the frames themselves.

**Comment by fpoli** [comment]
Carbon currently does not fully support loops formed via labels and gotos, which Prusti generates (https://github.com/viperproject/carbon/issues/182).

**Comment by Aurel300** [comment]
Maybe we can close this as we are not currently using Carbon?

**Comment by vakaras** [comment]
> Maybe we can close this as we are not currently using Carbon?

I think we should make Carbon to work, so I would prefer to keep this issue.

**Comment by fpoli** [comment]
Loops are now supported, but Carbon is extremly slow. I'm closing this issue because it's specific to loops.
