### ISSUE TITLE
Prusti tries to generate code for trait function without a body

### ISSUE THREAD

**Issue by jorajeev** [viperproject/prusti-dev#16]
Prusti complains about the following program
```
extern crate prusti_contracts;

trait Val {
    #[pure]
    fn value(&self) -> i32;
}

struct Foo<T> {
    x: T,
}

impl<T: Val> Foo<T> {
    fn get(&self) -> i32 {
        self.x.value()
    }
}
```
with the error
`librustc_mir/build/mod.rs:40: can't build MIR for DefId(0/0:5 ~ test[8787]::Val[0]::value[0])`
It appears to be trying to generate code for the empty `value` function in the trait.

**Comment by fpoli** [comment]
Thanks for the report. Support for specifications in trait definition is still not complete, thus the bug. Anyway, Prusti should either point out the currently unsupported specification or just work as expected.

**Comment by alexanderjsummers** [comment]
I think this issue highlights a second issue; we need to support `#[pure]` on functions which don't have bodies.

**Comment by fpoli** [comment]
Support for pure abstract trait methods in Prusti has been discussed in [Sec. 3.2.3 "Pure Functions" of this MSc thesis](https://ethz.ch/content/dam/ethz/special-interest/infk/chair-program-method/pm/documents/Education/Theses/Matthias_Erdin_MA_report.pdf). We should consider that. The document contains some nice examples.

**Comment by jorajeev** [comment]
Here's a more nontrivial example (attempting to implement a generic version of binary search).

```
extern crate prusti_contracts;

// A trait that says every member of a type can be assigned an integer value.
pub trait Val {
    #[pure]
    #[trusted]
    fn value(&self) -> i32;
}

pub struct VecWrapper<T> {
    v: Vec<T>,
}

// Vector of objects that support the `Val` trait above
impl<T> VecWrapper<T>
where
    T: Val,
{
    #[trusted]
    #[pure]
    pub fn len(&self) -> usize {
        self.v.len()
    }

    #[trusted]
    #[pure]
    #[requires = "0 <= index && index < self.len()"]
    pub fn value(&self, index: usize) -> i32 {
        self.v[index].value()
    }
}

pub enum UsizeOption {
    Some(usize),
    None,
}

impl UsizeOption {
    #[pure]
    pub fn is_some(&self) -> bool {
        match self {
            UsizeOption::Some(_) => true,
            UsizeOption::None => false,
        }
    }
    #[pure]
    pub fn is_none(&self) -> bool {
        match self {
            UsizeOption::Some(_) => false,
            UsizeOption::None => true,
        }
    }
}

// This implements binary search for any type that implements `Val` above.
// The result will be an element of the array that maps to the same value.
// Comparisons between two elements `x` and `y` are done by comparing
// `x.value()` and `y.value()`.
#[requires = "forall k1: usize, k2: usize :: (0 <= k1 && k1 < k2 && k2 < arr.len()) ==> arr.value(k1) <= arr.value(k2)"]
#[ensures = "result.is_none() ==>
            (forall k: usize :: (0 <= k && k < arr.len()) ==> arr.value(k) != elem.value())"]
#[ensures = "match result {
                UsizeOption::Some(index) => (
                    0 <= index && index < arr.len() && arr.value(index) == elem.value()
                ),
                UsizeOption::None => true,
            }"]
fn binary_search<T: Val>(arr: &VecWrapper<T>, elem: &T) -> UsizeOption {
    let mut size = arr.len();
    let mut base = 0usize;

    let mut result = UsizeOption::None;
    let mut continue_loop = size > 0;

    #[invariant = "continue_loop == (size > 0 && result.is_none())"]
    #[invariant = "base + size <= arr.len()"]
    #[invariant = "forall k1: usize, k2: usize :: (0 <= k1 && k1 < k2 && k2 < arr.len()) ==> arr.value(k1) <= arr.value(k2)"]
    #[invariant = "forall k: usize:: (0 <= k && k < base) ==> arr.value(k) < elem.value()"]
    #[invariant = "result.is_none() ==>
                (forall k: usize :: (base + size <= k && k < arr.len()) ==> elem.value() != arr.value(k))"]
    #[invariant = "match result {
                    UsizeOption::Some(index) => (
                        0 <= index && index < arr.len() &&
                        arr.value(index) == elem.value()
                    ),
                    UsizeOption::None => true,
                }"]
    while continue_loop {
        let half = size / 2usize;
        let mid = base + half;

        let mid_element = arr.value(mid);
        base = if mid_element < elem.value() {
            mid
        } else if mid_element > elem.value() {
            base
        } else {
            result = UsizeOption::Some(mid);
            base // Just return anything because we are finished.
        };

        size -= half;
        continue_loop = size > 0 && result.is_none();
    }

    result
}

fn main() {}
```

**Comment by f4z3r** [comment]
Ok so I found some time to reason about this a little. The problem comes down to how pure functions are handled when they are defined in traits. This problem is twofold:

1. Pure functions without a body.
2. Pure functions with a body that can be overwritten by trait implementations.

In the first case, the pure attribute guarantees two things:

1. The function is side-effect free.
2. The function is fully deterministic on input.

Since there is no implementation that can be used to complement the contract, these are the only two things that can be relied upon in contracts (assuming the pure function/method declaration does not provide additional contract attributes). In my opinion this has a use-case, mostly due to the second property: inequality of output implies inequality of input. A sample use case can be seen in the code snippet from @jorajeev above, or even a very simple one:

```rust
trait Hashable {
    #[pure]
    fn hash(&self) -> u32;
}

#[ensures="if result {
    true
} else {
   val1 != val2
}"]
fn is_hash_collision<T>(val1: &T, val2: &T) -> bool where T: Hashable + Eq { ... }
```

> Note that the preceding snippet contains a contract that is logically correct, no matter the implementation of `hash`. This is important as the contract should not rely on `hash` to be implemented sensibly (or correctly), only that the implementation is pure.

The first property could easily be represented by another attribute (e.g. `#[no-side-effect]`) as it does not allow the function to be used in contracts. So I think the second property is the interesting one. Regarding how to handle this logically, IMO Prusti should essentially encode the function somehow such that only the two properties are considered. Then Prusti could verify the implementation of `is_hash_collision`, for instance in the case of the trivial implementation:

```rust
#[ensures="if result {
    true
} else {
   val1 != val2
}"]
fn is_hash_collision<T>(val1: &T, val2: &T) -> bool where T: Hashable + Eq {
    val1.hash() == val2.hash()
}
```

> This should be verifiable without need of a concrete type for `T` or a concrete implementation of `hash`.

---

For the second case of over-writable pure functions, there are (IMHO) two ways to handle them:

1. Let the verification make use of the default implementation.
2. Not let it use the default implementation.

In the first case, Prusti would have to verify that every trait implementation actually implements the exact same behaviour than the default implementation (but could for instance use different algorithms to compute the same behaviour). One potential way to do this would be to consider the pure functions as simply one large expression containing the input parameters and returning the result. These two expressions are simple Rust expressions and can be verified for equality on verification boundaries (or contracts using the pure trait function could be duplicated for both implementations and then conjucted). This is possible for simple pure functions, but I am a little unsure how easy this would be to implement as the expression grow complex (using loops/branching, etc).

In the second case, it would essentially be the same as treating the pure trait function as empty (no implementation), and only considering the default implementation when verifying for a concrete type implementing the trait but not over-writing the default implementation of the pure function. For types that overwrite it, consider only the new implementation when reasoning with concrete types. This method guarantees correctness, as every implementation has to be pure (and potentially adhere to additional contract attributes declared in the trait definition), and therefore every method implementation (whether default or overwrite) represents a behavioural "subset" (stronger postcondition guarantees).

This essentially means, I think it all comes down to being able to encode the meaning of a `pure` function in Viper, without having to provide a concrete implementation for such a function. I currently have way too little experience with Viper to be able to formulate a solution to this.

---

PS: another use case might result from invariant attributes on marker traits (this is not supported but a current goal):

```rust
trait PartialEq {
    #[pure]
    fn eq(&self, other: &Self) ->  bool;
}

#[invariant="self.eq(self)"]
trait Eq: PartialEq { }
```

**Comment by Aurel300** [comment]
The two programs originally posted by @jorajeev verify, as well as an additional variant of the binary search (most of the loop invariants are unnecessary).

Re: the discussion by @f4z3r. Trait functions and methods can now be marked `#[pure]`, even without a default implementation. Encoding-wise, we emit a bodyless Viper function, which means the function is seen as both side-effect-free and deterministic. Implementations of such a method must also be pure.

The implementation refinement check (strengthening of a `post == <encoded expr>` "postcondition") is not yet enforced, so this verifies, although it should not:

```
trait Foo {
    #[pure] fn value(&self) -> i32 { 5 }
}

struct Bar {}
#[refine_trait_spec]
impl Foo for Bar {
    #[pure] fn value(&self) -> i32 { 10 }
}
```

This might be something to look into for @dewert99 ?

Finally, marker traits and invariants are something we can now do with type-dependent contracts/ghost constraints, although the feature is still in early stages.
