### ISSUE TITLE
Prusti generating illegal Viper code when overflow checking is enabled

### ISSUE THREAD

**Issue by jorajeev** [viperproject/prusti-dev#17]
I have a Prusti.toml file with
`CHECK_BINARY_OPERATIONS = true`
Prusti then panics with the following program
```rust
extern crate prusti_contracts;

#[requires = "x > 0"]
fn int_sqrt(x: i32) -> i32 {
    let mut r = 0;

    #[invariant = "(r * r) <= x"]
    while (r + 1) * (r + 1) <= x {
        r += 1;
    }

    r
}

fn main() {}
```
Commenting out the definition of `CHECK_BINARY_OPERATIONS` in `Prusti.toml` makes the panic go away, but then it complains about overflow, which is also strange, as the default behavior should be not to check for overflow.

**Comment by fpoli** [comment]
Thanks for reporting this!

With overflow checks enabled Prusti panics because the evaluation of `(r + 1) * (r + 1) <= x` is not free from side effects: the evaluation might panic, and abruptly terminate the loop. This is an incompleteness of Prusti, and the warning `[Prusti] this is partially supported, because it causes abrupt loop terminations` hints at it (I'm open to suggestions for a better error message).

With overflow checks disabled this program should be fully supported, so the error message about overflows is a bug. From a quick look, for some reason the CFG that Prusti gets from the compiler contains the overflow checks. This is not expected and causes the weird behaviour.

A temporary workaround is to evaluate the loop guard in a local variable:
```rust
extern crate prusti_contracts;

#[requires = "x > 0"]
fn int_sqrt(x: i32) -> i32 {
    let mut r = 0;

    let mut guard = (r + 1) * (r + 1) <= x;
    #[invariant = "(r * r) <= x"] // Prusti correctly points out a verification error here
    while guard {
        r += 1;
        guard = (r + 1) * (r + 1) <= x;
    }

    r
}

fn main() {}
```

**Comment by fpoli** [comment]
Actually, Prusti never dictates to the compiler whether to generate or not overflow checks in MIR. If the compiler generates these checks, and `CHECK_BINARY_OPERATIONS` is enabled, then Prusti actually checks for overflows. If the runtime checks are not generated, or if `CHECK_BINARY_OPERATIONS` is disabled, then Prusti doesn't check for overflows.

What happens, in the second case in the description of the issue, is that Prusti receives a program containing runtime overflow checks in the evaluation of the loop guard while `CHECK_BINARY_OPERATIONS` is disabled. Prusti should either understand that in this case the evaluation of this loop guard has no side effects, or prevent these checks from being generated by the compiler.

With this understanding, a second workaround for the case where `CHECK_BINARY_OPERATIONS` is disabled is to manually pass from the command line a compiler flag to avoid the runtime checks from being generated:
```
prusti-rustc -C opt-level=3 program.rs
```

**Comment by fpoli** [comment]
Closing because Prusti now supports loops with complex CFG shapes, so the loop above is supported. Using the new syntax:

```rust
use prusti_contracts::*;

#[requires(0 < x)]
fn int_sqrt(x: i32) -> i32 {
    let mut r = 0;

    while (r + 1) * (r + 1) <= x { // assertion might fail with "attempt to multiply with overflow"
        body_invariant!((r + 1) * (r + 1) <= x);
        r += 1;
    }

    r
}

fn main() {}
```

The program does not verify because the multiplication might overflow, as expected because the invariant is checked after the evaluation of the loop condition. Making the program verify is a different issue. If you have questions about that, consider asking on https://prusti.zulipchat.com/.
