### ISSUE TITLE
Unify handling of configuration flags

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-dev#184]
Currently, there are two ways to set configuration flags: the `-Z` arguments and the flags defined using the `config` crate. This leads to some code duplication and maintenance is error prone.

It would be nice to automatically read configuration flags from the `-Z` arguments by implementing the [Source](https://docs.rs/config/0.10.1/config/trait.Source.html) trait of the `config` crate.

**Comment by fpoli** [comment]
This is a good first issue for new contributors! :muscle:

Please ask for more information in case you are interested.

**Comment by gavinleroy** [comment]
I am interested in working on this issue. Is there any additional information I can get to work on it?

**Comment by vakaras** [comment]
Hello @gavinleroy!
All configuration options that Prusti uses are defined in [config.rs](https://github.com/viperproject/prusti-dev/blob/master/prusti-common/src/config.rs). As you can see from the file, there are two types of them:
1. [Command line flags](https://github.com/viperproject/prusti-dev/blob/master/prusti-common/src/config.rs#L59-L70): each field in that struct is [parsed by the driver](https://github.com/viperproject/prusti-dev/blob/864ff5677901367501a01b7f2b65e689ff37953e/prusti/src/driver.rs#L150-L163) and fed down.
2. [SETTINGS lazy object](https://github.com/viperproject/prusti-dev/blob/master/prusti-common/src/config.rs#L74-L113) that is initialized from `Prusti.toml` and environment variables.

Until recently, these two sets of settings were completely disjoint. However, recently I had to allow changing one of the `SETTINGS` via [a command-line flag](https://github.com/viperproject/prusti-dev/blob/864ff5677901367501a01b7f2b65e689ff37953e/prusti/src/driver.rs#L162-L163). Therefore, we think it would be good to merge command-line flags into the `SETTINGS` object by implementing the aforementioned `Source` trait.

@fpoli Did I forget anything?

@gavinleroy Is it clear how to proceed?

**Comment by gavinleroy** [comment]
@vakaras Yes, that is clear. 

I do have two questions regarding changes to the `ConfigFlags` struct: 

1) Currently, in the `ConfigFlags` struct there isn't a field for the [-Zdisable_more_complete_exhale](https://github.com/viperproject/prusti-dev/blob/864ff5677901367501a01b7f2b65e689ff37953e/prusti/src/driver.rs#L162-L163) flag. Since `ConfigFlags` will now be merged with the `SETTINGS` object, would it be reasonable to give the struct a dedicated boolean field for it? For example, the new struct definition would become: 
```rust
#[derive(Clone, Copy)]
pub struct ConfigFlags {
    /// Should Prusti print the AST with desugared specifications.
    pub print_desugared_specs: bool,
    /// Should Prusti print the type-checked specifications.
    pub print_typeckd_specs: bool,
    /// Should Prusti print the items collected for verification.
    pub print_collected_verfication_items: bool,
    /// Should Prusti skip the verification part.
    pub skip_verify: bool,
    /// Should Prusti hide the UUIDs of expressions and specifications.
    pub hide_uuids: bool,

    /// Should Prusti enable the more complete exhale in the verifier.
    pub use_more_complete_exhale: bool, // <- NOTE: new field
}
```
You'll notice that `ConfigFlags` could no longer derive the `Default` trait because the default for `USE_MORE_COMPLETE_EXHALE` is true, as seen [here](https://github.com/viperproject/prusti-dev/blob/864ff5677901367501a01b7f2b65e689ff37953e/prusti-common/src/config.rs#L99). The `Default` trait would have to be implemented as well. 

2) Could I move this [if-block](https://github.com/viperproject/prusti-dev/blob/ee5def9423f99af974300d8d7d1a43377354e8cf/prusti/src/driver.rs#L152-L163) into a function implemented for `ConfigFlags`? Doing so would allow all of the configuration code to be contained to the [config.rs](https://github.com/viperproject/prusti-dev/blob/master/prusti-common/src/config.rs) file. I think this would make it more straightforward to modify command line argument functionality in the future. E.g. adding an argument would only require changes to the config.rs file.

**Comment by vakaras** [comment]
Let's remove `ConfigFlags` completely. This will change the command-line arguments completely and will require updating UI tests, but, I think, is worth it. The idea would be:

1. Create new struct `CommandLinePrustiOptions` that represents all Prusti options passed via command line. Implement [Source](https://docs.rs/config/0.10.1/config/trait.Source.html) trait for it.
2. Create a new function that takes a list of command-line arguments and filters out the ones that start with `-P`. Note that I would like to avoid having a huge if/match statement that manually checks for every possible command-line option (basically, the only place that lists all available options should be [this](https://github.com/viperproject/prusti-dev/blob/ee5def9423f99af974300d8d7d1a43377354e8cf/prusti-common/src/config.rs#L78-L113) block that sets the default values). However, if we were to use `-Z` as a prefix, we could not avoid that because we could not distinguish Prusti options from Rustc options. That is why we need a different prefix.
3. The same function could instantiate `CommandLinePrustiOptions` with the filtered out arguments and [merge it](https://github.com/viperproject/prusti-dev/blob/ee5def9423f99af974300d8d7d1a43377354e8cf/prusti-common/src/config.rs#L116-L129) into `SETTINGS`.

This design will require to add all missing flags from `ConfigFlags` to `SETTINGS`. The command line flag `-Zdisable_more_complete_exhale` would be replaced with `-Puse_more_complete_exhale=false`.

> Could I move this if-block into a function implemented for ConfigFlags?

This if-block should be completely gone and replaced by a generic parser of arguments that have shape `-Parg=val`.

**Comment by gavinleroy** [comment]
That is much more clear, thank you!

**Comment by fpoli** [comment]
> @fpoli Did I forget anything?

No, I think that's all. I'm very happy that this is going to be worked on. Two suggestions:

* Try to keep the new struct `CommandLinePrustiOptions` Prusti-agnostic (we could even remove Prusti from the name), so that we can upstream it to [config-rs](https://github.com/mehcode/config-rs) right after it's in Prusti. I'm sure many other crates will benefit from it.
* For testing, you can take inspiration from [config-rs's tests](https://github.com/mehcode/config-rs/blob/master/tests/env.rs).

**Comment by gavinleroy** [comment]
I wanted to give an update on what I've found / done in the last few days. 

* Implementing the `Source` trait on a struct within Prusti won't work due to privacy levels set in config-rs. 
To elaborate, one of the functions needed to implement `Source` is:
```fn collect(&self) -> Result<HashMap<String, Value>> { .... }``` 
The important thing to note here is the presence of [`Value`](https://docs.rs/config/0.10.1/config/struct.Value.html) in the return type. To create a new `Value`, a `ValueKind` needs to be specified. However, `ValueKind` is a private module. There is an [open issue](https://github.com/mehcode/config-rs/issues/62) documenting that `ValueKind` should be re-exported but it looks like there are plans to remove it altogether. So  I don't anticipate the privacy level changing.

* To continue, I forked the config-rs project and implemented a [CommandLine](https://github.com/gavinleroy/config-rs/blob/950072d8ef10b9a36d3536c60236f94cd773c743/src/commandline.rs#L7-L129) struct that would allow Prusti to have the desired functionality. I haven't written any real tests for it yet, however, I have tested it locally with Prusti. 
You can see that [merging](https://github.com/gavinleroy/prusti-dev/blob/092ea32a7ce6ba7ab38b22855060838090e28778/prusti-common/src/config.rs#L121-L124) with prior configurations is similar to other structs in config-rs and on this [branch](https://github.com/gavinleroy/prusti-dev/tree/gavinleroy-184), I've completely removed the need for the old `ConfigFlags` struct. 
Any configuration can be overwritten or included as a command-line argument following the pattern `-P<arg>=<val>`.

I plan to submit a PR to config-rs (after I've written a few tests) with the hopes that the new struct can get merged in the near future. It appears that development in config-rs is fairly stagnant and I'm unsure how quickly anything will get integrated into the crate. 
If you have any suggestions on how to proceed from here or feedback on my [code changes to Prusti](https://github.com/viperproject/prusti-dev/compare/master...gavinleroy:gavinleroy-184), it would be very much appreciated.

**Comment by vakaras** [comment]
> To create a new `Value`, a `ValueKind` needs to be specified. However, `ValueKind` is a private module.

As far as I see, `new` requires not a `ValueKind`, but `Into<ValueKind>`. Therefore, using the value directly “should just work”. For example:

```rust
let x = config_crate::Value::new(None, String::from("42"));
let y = config_crate::Value::new(None, true);
let z = config_crate::Value::new(None, 42i64);
```

Is there some other reason why this does not work?

>  implemented a `CommandLine` struct that would allow Prusti to have the desired functionality

Looks good. I am just wondering whether it would not be better to change `is_valid_arg` so that it accepts `<prefix><identifier><separator><anything>`. This would, for example, be useful for allowing to provide additional arguments to backends: `-Pextra_verifier_args=--dump-smt-log=true --smt-log-file=log`.

> You can see that merging with prior configurations is similar to other structs in config-rs and on this branch, I've completely removed the need for the old ConfigFlags struct.

I like this. The code looks good to me. @fpoli Any comments from you?

> I plan to submit a PR to config-rs (after I've written a few tests) with the hopes that the new struct can get merged in the near future. 

I think it would be definitely useful to try to upstream your changes. In the meantime, we can change Prusti to git depend on your fork, so that we do not have a hanging PR.

**Comment by fpoli** [comment]
>I plan to submit a PR to config-rs (after I've written a few tests) with the hopes that the new struct can get merged in the near future. It appears that development in config-rs is fairly stagnant and I'm unsure how quickly anything will get integrated into the crate. If you have any suggestions on how to proceed from here or feedback on my code changes to Prusti, it would be very much appreciated.

Thanks for pointing this out; I was not aware of the maintenance problems of the last year. Sure, go ahead with the PR. I think we should ask on https://users.rust-lang.org/ if there are (sufficiently experienced) developers that are willing to help maintaining config-rs.

> I forked the config-rs project and implemented a CommandLine struct that would allow Prusti to have the desired functionality.

Really nice and clean, indeed! Regarding the normalization of keys, I think it's good to convert them to lowercase like `Environment` does. Adding some tests should be easy.

**Comment by gavinleroy** [comment]
> Is there some other reason why this does not work?

There is no reason why this doesn't work, I'm a little embarrassed that I overlooked that detail. With that information, this change can be merged into Prusti (sooner) and then upstreamed to config-rs later. 

> I am just wondering whether it would not be better to change is_valid_arg so that it accepts <prefix><identifier><separator><anything>. This would, for example, be useful for allowing to provide additional arguments to backends: -Pextra_verifier_args=--dump-smt-log=true --smt-log-file=log.

That does seem like a useful feature to have, I've updated how the [argument is split](https://github.com/gavinleroy/prusti-dev/blob/5b12726d62ffafd5de26894ef068a28de0da00d2/prusti-common/src/config/commandline.rs#L68-L71) to reflect this. 

> Adding some tests should be easy.

I updated the UI tests in Prusti to reflect these changes and submitted a PR #325

**Comment by vakaras** [comment]
> I updated the UI tests in Prusti to reflect these changes and submitted a PR #325

I have merged your PR. Thank you for fixing this!
