### ISSUE TITLE
Prusti attributes do not work across crates

### ISSUE THREAD

**Issue by karroffel** [viperproject/prusti-dev#2]
**Describe the error**
Attributes such as `#[pure]` or `#[requires]` are not taken into consideration across multiple crates. 

**To Reproduce**
Unpack the attached `.zip` file and run `cargo-prusti` and observe that the `#[pure]` annotation is assumed to be missing even when it's there.

Alternatively, this is pretty easy to set up manually.

1. Create a cargo workspace or have two (or more) empty crates available. (at least one of them as a lib-crate) 
2. add the necessary declarations (`extern crate prusti_contracts`) and have one crate depend on a lib-crate by modifying the `Cargo.toml`.
3. Add a function to the lib crate with any prusti-attributes (`#[pure]`, `#[requires]` and `#[ensures]` have been tested)
4. Use the function from the lib crate inside the "consumer" crate in a way that demonstrates if the attributes are respected (using `#[pure]` function inside of a pre/post-condition, violating the `#[requires]`-clause or `assert!`-ing on `#[ensures]` properties)
5. Run `cargo-prusti` and observe that those attributes do not have the desired effect (not marked as `#[pure]`, no `#[requires]`-violation found or `assert!` fails)

**Expected behavior**
Attributes should work across crate boundaries just as they work within a single crate.

**Reproduction project or code sample**
[pure-across-crates.zip](https://github.com/viperproject/prusti-dev/files/3381838/pure-across-crates.zip)

```rust
// crate producer
extern crate prusti_contracts;

#[pure]
pub fn five() -> usize {
    5
}
```

```rust
// crate consumer
extern crate prusti_contracts;
extern crate producer;

use producer::five;

#[requires="five() == 5"]
pub fn _test() {}
```

**Software configuration:**
Using `fpoli/prusti-artefact` docker image from `09 July 2019`

**Comment by fpoli** [comment]
Thanks for the report! We'll probably not fix this right now because we first would like to rewrite the component that parses and type-checks the specifications, using procedural macros instead of rewriting the AST while running Prusti. This would allow to upgrade the Rust compiler version by Prusti, but it's not a small change.

In the meantime, a workaround is to wrap every imported pure function in a new trusted-pure function, writing an appropriate postcondition. This way, Prusti doesn't lookup the contract from the external crate. For example:

```rust
// crate consumer
extern crate prusti_contracts;
extern crate producer;

use producer::five;

#[pure]
#[trusted]
#[ensures="result == 5"]
fn five_wrapper() {
    five()
}

#[requires="five_wrapper() == 5"]
pub fn _test() {}
```

In this case the workaround is not very helpful, but it might be useful on other examples.

**Comment by fpoli** [comment]
More precisely, this issue originates [here](https://github.com/viperproject/prusti-dev/blob/d8fd79355c4ff2a84f9fa21a0d5278effe720297/prusti-viper/src/encoder/encoder.rs#L305..L310):
```rust
pub fn get_spec_by_def_id(&self, def_id: DefId) -> Option<&TypedSpecificationSet> {
        // Currently, we don't support specifications for external functions.
        // Since we have a collision of PRUSTI_SPEC_ATTR between different crates, we manually check
        // that the def_id does not point to an external crate.
        if !def_id.is_local() {
            return None;
        }
       ...
}
```

**Comment by fpoli** [comment]
Actually, to fix the issue it should be enough to generate specification ids that do not conflict between crates, removing then the `return None` mentioned above. If someone wants to give a try at it I can provide more hints.

**Comment by karroffel** [comment]
I would be willing to try it out, hints would be very welcome as I've never worked with the rustc-internals :smile:

**Comment by fpoli** [comment]
Here are some suggestions; there are one or two necessary changes that make it less trivial to fix than I though. I would say that it's 70% about Prusti internals and 30% about rustc internals :)

Prusti needs to type-check the user-provided specifications, to reject thinks like
```rust
#[requires="true / 2 == 'x'"]
```
This is done in the `rewrite_crate` function by generating for each specification some Rust code (closures, mostly) that type-checks if (and only if) the original specification type-checks. Each specification and each snippet of generated code has an ID which links them together. This ID is stored as Rust attributes (`__PRUSTI_SPEC`, `__PRUSTI_EXPR_ID`, ...) in the generated code. You can inspect this generated code by running Prusti with the `PRUSTI_DUMP_DEBUG_INFO` environment variable set to `true`; with this flag, Prusti dumps the code in the `log/rust_crate_before_typechecking*` folder.

Also expressions have a unique identifier used for type-checking. Both IDs are generated in `prusti-interface/src/parser.rs`:
```rust
    /// Generate a fresh specification ID (guaranteed to be unique).
    fn get_new_specification_id(&mut self) -> SpecID {
        self.last_specification_id.inc()
    }

    /// Generate a fresh expression ID (guaranteed to be unique).
    fn get_new_expression_id(&mut self) -> ExpressionId {
        self.last_expression_id.inc()
    }
```

The issue is that each crate is compiled and verified independently, so in each crate the IDs start from `0`. If the program verified by Prusti wants the contract of an external function there is no way to look it up with an ID. One solution is to add to each ID (`SpecID`, `ExpressionId`) something that uniquely identifies the crate. For example:
* the name of the crate (e.g. as a string) with its `crate_disambiguator` (it's a field of the `Session` compiler structure, which is accessible from the `CompileState` structure, which is an argument of the `rewrite_crate` function);
* otherwise, a sufficiently large randomly generated UUID.

To fix the issue I would say that the main steps are:
1. Remove the `if !def_id.is_local() { return None; }` from the snipped mentioned in a previous message, and find an example on which Prusti picks the wrong specification from an external crate due to the collision in the IDs.
2. Add to `SpecID` and `ExpressionId` a field that uniquely identifies the crate, propagating the change to all usages of those ids (including the conversion to and from string, used to store the id in Rust attributes).
   * It's probably easier to initially generate a random number to identify the crate, and later refactor to use the crate name and crate disambiguator that the compiler offers.
3. Change `type_specifications`, the component that walks over functions and collects specifications IDs from the attributes, such that it does not walk over [HIR](https://rust-lang.github.io/rustc-guide/hir.html?the-hir), but over [MIR](https://rust-lang.github.io/rustc-guide/mir/index.html) items. This because HIR is not available for external crates, but MIR items yes.
   * Useful methods to walk over MIR items and get attributes are [`mir_keys`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/struct.TyCtxt.html#method.mir_keys) and [`get_attrs`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/struct.TyCtxt.html#method.get_attrs).
   * As a consequence, HIR types should disappear from `specifications.rs`, to be replaced just with the `Span` data.
4. Check that the issue introduced in step 1 is solved.

For debugging it's useful to set `RUST_LOG` to `info` or `debug`. To lookup the available compiler API I usually search (with grep, or with a full text search in Clion/IDEA) in the source code of the compiler, but another option is to compile rustc setting the flag to generate the html documentation or just use the [latest documentation](https://doc.rust-lang.org/nightly/nightly-rustc/rustc) hoping that it's still valid. Prusti uses the compiler version `nightly-2018-06-27`, so to get the correct version of the compiler's source code it's necessary to checkout to a commit around `2018-06-27`. A general introduction to compiler internals is [here](https://rust-lang.github.io/rustc-guide/). However, our version of the compiler is now 1-year old, so there might be some differences from the online documentation.

**Comment by karroffel** [comment]
Thank you very much for this description!

I tried to start working on this by setting everything up for development. I could not get hold of any meaningful documentation for the rustc-internal crates such as `rustc_driver`. It seems like the compiler changed quite a bit since mid 2018, I could not find docs for `CompileState` for example.

It also seems like there is no way to get rustc sources via rustup so I will set up the Rust compiler tomorrow.

**Comment by karroffel** [comment]
I did work on this and only added the `CrateDisambiguator` to `SpecID` and `ExpressionId` but I noticed that also the name of the crate has to be stored. What would be the best way to do this?

Having every SpecID have a `String` member seems very much overkill. Introducing a lifetime and using `&str` also seems quite complex since all IDs would carry around lifetimes now.

Maybe an `Arc<String>` can be used, but when reading an ID from the attributes it would not increment the reference count and create a new `Arc` instead. This could be solved by having a kind of `CrateRegistry` which can be used to look up the `Arc`.

None of those seem particularly good solutions. Maybe the name could be hashed and a `u64` could be used as a crate-id, but this might carry other problems with it.

**Comment by vakaras** [comment]
I agree that none seem to be really good solutions. Personally, I would go with having a `String` member just because of its simplicity.

There is also [CrateNum](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/hir/def_id/enum.CrateNum.html), which is the internal crate id used by the compiler that can be converted to `usize`. However, I am not sure how stable it is.

**Comment by fpoli** [comment]
I agree with @vakaras: I would also go with `String`.

If I remember correctly the problem with `CrateNum` (and with a `CrateRegistry`) is the same problem that we have with specification IDs: at each compilation they start from zero and it is not possible to reuse them across compilations. To avoid this, a `CrateRegistry` should store the mapping to disk, but for the moment I don't think that it is worth it.

**Comment by fpoli** [comment]
An interesting compilation-independent key to store on disk annotations per MIR bodies is provided by the [`StableHash` trait](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/struct.Body.html#impl-HashStable%3CStableHashingContext%3C%27__ctx%3E%3E):

> Stable hashes are sometimes used as identifiers. Therefore they must conform to the corresponding PartialEq implementations [...]
