### ISSUE TITLE
Non-deterministic failure in fold/unfold with enums

### ISSUE THREAD

**Issue by Aurel300** [viperproject/prusti-dev#362]
```rust
use prusti_contracts::*;

enum MyOption {
    None,
    Some(i32),
}

impl MyOption {
    #[pure]
    fn is_some(&self) -> bool { matches!(self, MyOption::Some(_)) }
    #[requires(
        self.is_some() ==>
        5 == match self {
            MyOption::Some(n) => n,
            MyOption::None => unreachable!(),
        }
    )]
    #[trusted]
    fn map(self) -> MyOption { unimplemented!() }
}

fn main() {
    MyOption::None.map();
}
```

Sometimes fails during fold/unfold, sometimes gets to the verifier. The error is one of:

- `Consistency error: state has pred _2[enum_None] (write), but also pred _2 (write)`
- `Consistency error: state has acc _2[enum_Some], but also pred _2`
- (in the verifier) `Unfolding m_MyOption$_beg_$_end_Some(_2.enum_Some) might fail. There might be insufficient permission to access m_MyOption$_beg_$_end_Some(_2.enum_Some)`

**Comment by vakaras** [comment]
@Aurel300 The problem seems to be contradictory requirements for the folding state in the `MyOption::map` precondition. `_2` is required to be both folded (by `is_some`) and unfolded (by `_2.discriminant`). Since the assert statement uses `Stmt` folding behaviour, these requirements cannot be satisfied.

The current VIR encoding:
```plain
    // [mir] _1 = MyOption::map(move _2) -> [return: bb1, unwind: bb2]
    label l0
    assert(Stmt) ((m_is_some<Ref(m_MyOption$_beg_$_end_),Bool>(_2)) ==> (((_2.discriminant) == (0))?(builtin$unreach_bool<,Bool>()):((5) == (_2[enum_Some].f$0.val_int)))) && (true)
    assert(Stmt) (m_MyOption$_beg_$_end_$inv<Ref(m_MyOption$_beg_$_end_),Bool>(_2)) && (true)
    exhale (acc(m_MyOption$_beg_$_end_(_2), write)) && (true)
```

A possible fix would be to replace the folding behaviour of assert to `Expr` and obtain the folding state that is used when exhaling the permissions.

**Comment by fpoli** [comment]
Currently the fold unfold algorithm does not try to resolve contradictory requirements; it just collects requirements from the expressions used in a statement. The proper fix would be to solve conflicts by removing requirements that can be obtained by unfolding from another requirement. For example, given `_2` and `_2.discriminant`, `_2.discriminant` can be obtained by unfolding `_2`, so only `_2` should be kept.
