### ISSUE TITLE
Installation from source on a Mac

### ISSUE THREAD

**Issue by Lee-Janggun** [viperproject/prusti-dev#365]
I was trying to install Prusti from the source following [this guide](https://viperproject.github.io/prusti-dev/dev-guide/development/). On the build stage, I would always fail with the following error:

```
Caused by:
  process didn't exit successfully: `/Users/janggun/Documents/prusti-dev-master/target/debug/build/viper-sys-3f1e07a295d1a225/build-script-build` (signal: 6, SIGABRT: process abort signal)
 --- stderr
  dyld: Library not loaded: @rpath/libjli.dylib
    Referenced from: /Users/janggun/Documents/prusti-dev-master/target/debug/build/viper-sys-3f1e07a295d1a225/build-script-build
    Reason: image not found
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I looked into the python build script, and it seems that this place was the problem. 

https://github.com/viperproject/prusti-dev/blob/22a4eb83ef91391d9a91e6b3246ddf951b8eb251/x.py#L88-L91

When printing out the actual filenames in `files`, the files always had a b attached to the front. So one should check for `b'libjli.dylib'`, not just `'libjli.dylib'`. Making this change fixed the problem and it built just fine.

**Comment by Aurel300** [comment]
Thanks for reporting this. This is interesting, I have also experienced similar failures on OS X, although I have switched to a different OS since. Locally, this change would not make sense:

```python3
>>> for root, _, files in os.walk(java_home):
...   if "libjli.dylib" in files:
...     print(files)
... 
['libjli.dylib']
```

However, if I make `java_home` be a `bytes` object instead of a `str`, I do need `b"libjli.dylib"`. For the script, we could try to check if the path is a `str` object and encode it into `bytes` if so.

**Comment by fpoli** [comment]
Thanks for the report. It seems that `os.walk(java_home)` returns strings of the same type of the argument, so the issue is that `java_home` is sometimes a byte string. The `JAVA_HOME` environment variables is read as a unicode string, while the `java_home = subprocess.run(..).stdout.strip()` returns a *byte* string. So, the fix would be to add `encoding="utf8"` to the arguments of `subprocess.run(..)`.
