### ISSUE TITLE
Add support for quantifying over copy types

### ISSUE THREAD

**Issue by vakaras** [viperproject/prusti-dev#56]
Currently, Prusti allows quantification only over primitive types. However, once we have snapshots as part of #53, we could support quantification over `Copy` types by quantifying over snapshots.

**Comment by FabianWolff** [comment]
Speaking of quantification, how would you write a specification for this function?
```Rust
fn foo (v: &mut Vec<&mut i32>) {
    for num in v {
        **num += 1;
    }
}
```
In Rust (from my understanding), there isn't even a clear meaning of "`v` contains the same references", because references are treated "by-value", meaning that `v` actually _doesn't_ contain the same references.

So perhaps something like this should work:
```
ensures: forall ref: &mut i32 :: old(v).contains(&ref)
             ==> (exists nref: &mut i32 :: v.contains(&nref) && *nref == *ref + 1)
```
But this needs both existential and universal quantification over a non-copy type (namely, `&mut i32` in this example).

And it gets worse:
```Rust
fn bar (v: &mut Vec<&mut i32>) {
    for num in v {
        **num = 0;
    }
}

let mut x = 1;
let mut v = vec! [&mut x];
bar (&mut v);
assert_eq! (x, 0);
```
Here, in the postcondition of `bar()`, it is _not_ enough to say that all references in `v` dereference to zero, we _also_ need to know that `&mut x` is still in `v` in order to prove the assertion...

What are your thoughts on this?

**Comment by cmatheja** [comment]
I'm not entirely sure about these examples because we do not properly support Vec yet.

Assuming support for Vec, I guess we can deal at least with the first example without quantifying over references. It should suffice to quantify over all positions in the vector, i.e., we could try something along the lines of

```
old(v).len() == v.len() && forall i: i32 :: old(*v[i]) == *v[i] + 1
```

The second example seems to be more of an issue.

**Comment by fpoli** [comment]
To annotate your `foo` and `bar` functions I would rather quantify over the index and use something like `old(*v[i]) == *v[i] + 1` in the postcondition, because there are many tricky things going on:
* `&mut i32` is not a copy type
* the semantics of quantifying over references is undefined (e.g. should it quantify over existing references? over all memory regions? over all memory regions for which holding a mutable reference is not UB? ...)
* types like `&mut Vec<&mut i32>` that contain references are not yet supported, mostly because of examples involving reborrowing (btw, @frececroka you might be interested in Fabian's examples)

**Comment by cmatheja** [comment]
> To annotate your foo and bar functions I would rather quantify over the index and use something like old(*v[i]) == *v[i] + 1 in the postcondition

I also first thought that this is the way to go. However, at least in Fabian's second example, I'm not convinced that using indices is enough. It seems that we still lose the knowledge that the mutable reference ```&mut x``` is contained in the vector and, consequently, that its value was changed to 0 (apart from the fact that various features used in the examples are not supported).

**Comment by fpoli** [comment]
> I also first thought that this is the way to go. However, at least in Fabian's second example, I'm not convinced that using indices is enough. It seems that we still lose the knowledge that the mutable reference &mut x is contained in the vector and, consequently, that its value was changed to 0 (apart from the fact that various features used in the examples are not supported).

In the second example I think you could get away with `forall i: i32 :: ... ==> *old(v[i]) == 0` in the postcondition, but I share the feeling that in general using indices might not be enough. In a way, the assertion above describes how values will look like, but does not describe how the topology of references changes.

**Comment by Aurel300** [comment]
This will be supported using snapshots, not only over `Copy` types.

**Comment by JonasAlaif** [comment]
@Aurel300 what is the status of this? I would like to do:
```rust
impl<T: Ord> Tree<T> {
    #[ensures( forall(|v: &T| ...) )]
    ...
}
```
With either `T` or `&T`, but currently Prusti complains that `T` is not a supported type, and for the latter (`&T`) straight up panics during the encoding.

**Comment by Aurel300** [comment]
@JonasAlaif `&T` is probably wrong. Other than that, the checks that you are finding can be disabled without crashing the verifier. Specifically:

https://github.com/viperproject/prusti-dev/blob/7977d30a028edfe0e300bb2931992d4029385b41/prusti-viper/src/encoder/high/types/fields.rs#L42

Here `TypeVar` can be moved to the "composed data structures" case, and:

https://github.com/viperproject/prusti-dev/blob/7977d30a028edfe0e300bb2931992d4029385b41/prusti-viper/src/encoder/foldunfold/requirements.rs#L328-L330

This can be disabled.

**However**: there is no test case I know of that tests that the type substitution works correctly with such a quantifier. Specifically, if there is an `ensures(forall(|v: T| ...))`, at the call site we would like to inhale a `forall(|v: X| ...)` if `X` is the concrete instantiation.

**Comment by Aurel300** [comment]
This is supported now.
