### ISSUE TITLE
Caching and incremental verification

### ISSUE THREAD

**Issue by enjhnsn2** [viperproject/prusti-dev#722]
Hello,
I was wondering how hard it would be to implement incremental verification in Prusti. Prusti verifies programs modularly at the function level, so it seems reasonable that with some minor modifications, Prusti would be able to cache the hashes of functions and contracts, and, if they don't change, just skip them. 
The semantics of this would look something like: `if hash(function + contract) == last_hash then function = trusted`.
I'm working on a verifying a relatively large project with prusti (2000+ loc), and Prusti takes roughly 20 minutes to verify right now. This time isn't too bad in itself, but having to wait 20+ minutes every time I edit the program is a bit rough, so I am quite interested in getting this to work.

If this would not be too difficult and you can point me to some relevant portions of code, I could take a crack at it.

**Comment by fpoli** [comment]
That would be nice. We discussed it a few times. Caching could be done at the Viper level, at the Rust level, or at both:
- At the Viper using in the `prusti-server` crate the new [`ViperCoreServer`](https://github.com/viperproject/viperserver/blob/3e7d117298c2c7766f25706eb0ccd360f33762d1/src/main/scala/viper/server/core/ViperCoreServer.scala#L21) API, which has built-in caching, instead of [manually creating Silicon and Carbon instances](https://github.com/viperproject/prusti-dev/blob/f9330b2a5eeed94e74a0f7e35e825daacb13f035/viper/src/verifier.rs#L55-L62) as we currently do. This sounds doable. It's mostly matter of crating the correct Java classes from Rust and learning the Viper API. I guess it would be a few hundreds of lines of code to change, but spread over `viper`, `viper-server` and `viper-common`. However, with this approach the cache would be lost as soon as you restart the server and it would not work if Prusti is nondeterministic in the generation of Viper code (it should not).
- At the Rust level, using a framework like [Salsa](https://github.com/salsa-rs/salsa) and (if possible) incremental compilation information coming from the compiler. This would require to refactor big portions of Prusti — I don't suggest it — but in the end it's the most efficient approach because it would even allow Prusti to skip the generation of Viper code for the Rust code that is guaranteed to be unchanged. The idea of `if hash(function + contract) == last_hash then function = trusted` is correct, but the hash would also need to depend at least on the hash of all the pure functions used in the contract, and all the type definitions used in the signature.

Have you checked in the Prusti log if the verification time is spent in Z3 or in the generation of Viper code? Viper-level caching would only help to reduce the former.

@viperproject/prusti-dev anything against using the new `ViperCoreServer` API? It shouldn't conflict with the ongoing refactoring.

**Comment by vakaras** [comment]
I see the following options for improving the experience of verifying large projects:

1. Add an option to Prusti Assistant to verify a single selected function. This would involve the following:

   1. In Prusti Assistant (the VS Code extension) add a keybinding that invokes ``cargo-prusti --verify-only <position of the cursor specified in some way>``.
   2. Implement ``--verify-only`` option in Prusti by traversing all functions, getting their spans from the compiler and checking whether the cursor is within the checked function.
   3. Put the found function into the [`annotated_procedures`](https://github.com/viperproject/prusti-dev/blob/7f2e8545e901429e5971f8f83234a3e8c3cbd68b/prusti/src/verifier.rs#L19) list instead of all functions in the program.

2. Cache the verification results of encoded programs. This should be quite easy to implement, but would potentially save only the verification time. This would involve the following:

   1. Compute hashes of [encoded Viper programs](https://github.com/viperproject/prusti-dev/blob/7f2e8545e901429e5971f8f83234a3e8c3cbd68b/prusti-viper/src/verifier.rs#L250).
   2. If the hash has not changed, return the stored verification result [instead of invoking the verifier](https://github.com/viperproject/prusti-dev/blob/7f2e8545e901429e5971f8f83234a3e8c3cbd68b/prusti-viper/src/verifier.rs#L272-L301).
   3. The hashes could be preserved by using the Rust compiler's incremental infrastructure. Creusot has [an example](https://github.com/xldenis/creusot/tree/master/creusot-metadata) how to do that.
   4. Note that positions of cashed error messages could be off if errors are cached in a naïve way.

3. Use the Rust compiler's incremental compilation infrastructure to figure out what was modified and use that information to compute [the set of functions](https://github.com/viperproject/prusti-dev/blob/7f2e8545e901429e5971f8f83234a3e8c3cbd68b/prusti/src/verifier.rs#L19) that need to be reverified. I do not see a way of implementing this that would not require large refactorings.

**Comment by enjhnsn2** [comment]
As far as I understand - it seems like https://github.com/viperproject/prusti-dev/pull/799 solves this issue. If issue 799 does what I think it does, then I can close this issue.

**Comment by vakaras** [comment]
@JonasAlaif

**Comment by JonasAlaif** [comment]
Yep I think we can close this. Do let me know if you have any issues with the caching
