### ISSUE TITLE
Cached programs do not dump their Viper encoding

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-dev#843]
When using the Prusti Server with `PRUSTI_DUMP_VIPER_PROGRAMS=true`, cached programs do not write their Viper encoding to disk. We might want that to happen anyway.

**Comment by vakaras** [comment]
I am not sure about this. As far as I understand the current implementation, if you get a cache hit, the Viper encoding is not even generated so supporting this is likely to introduce complexity and slow down.

**Comment by vakaras** [comment]
Wouldn't it be better to emit a warning/error telling that `dump_viper_programs` is not allowed when caching is enabled?

**Comment by Pointerbender** [comment]
As a data point that might help: sometimes when I am switching between multiple git branches of the Prusti repo, the Viper code generated by different revisions may all be cached, but then I can't get back different versions of the dumps if I didn't remember to make manual copies :sweat_smile: For me, this typically only happens when I'm debugging failing programs. Right now I worked around that by manually hard-coding to always run the verification (and dump the program) if the cached result is not `VerificationResult::Success`. Having a possibility to always dump the Viper program could help with this (also when verification fails and the result is cached).

Edit: the reason I don't delete the whole cache, is because for some Rust programs it takes 30-45 minutes for a full run. If only 1 or 2 methods are failing, it's cheaper to just only re-run the failed methods to generate the dumps.

**Comment by fpoli** [comment]
I'm happy either way. The slowdown would anyway be fractions of a second and it can be avoided if `dump_viper_programs` is disabled. The logic is all in the first two functions of `process_verification.rs`.

**Comment by JonasAlaif** [comment]
Good observation, I agree that this should be fixed even though that will be quite messy aha

**Comment by JonasAlaif** [comment]
The nice solution would be to dump the viper file from VIR Low (e.g. implementing the Display trait), but I'm not sure how much the two differ (VIR Low AST vs Viper AST) so maybe that's not possible?
In that case, `dump_viper_program` and `no_verify` could work together (currently the only way to dump the viper file without actually verifying is to set `print_hash`...)

**Comment by vakaras** [comment]
> The nice solution would be to dump the viper file from VIR Low (e.g. implementing the Display trait), but I'm not sure how much the two differ (VIR Low AST vs Viper AST) so maybe that's not possible?

The main motivation for dumping the Viper program is to be able to debug it in the Viper IDE. Therefore, it is extremely important that the output identically matches the AST, which is hard to achieve.
