### ISSUE TITLE
Prusti cache path from Prusti.toml overriden by cargo-prusti

### ISSUE THREAD

**Issue by emlaufer** [viperproject/prusti-dev#853]
I'm not sure if this is intended behavior or not, but currently it is impossible to provide a CACHE_PATH within a Prusti.toml file to cargo-prusti, because it is over-written with an environment variable in `cargo-prusti.rs` which takes priority that sets it to the default path of ./target/verify/CACHE.bin.

**Comment by vakaras** [comment]
Sounds like a bug. @JonasAlaif could you please look into this?

**Comment by JonasAlaif** [comment]
Thanks for reporting this! @vakaras this is not so much a bug as it is an awkwardness with how settings are handled by `cargo-prusti` and `prusti-rustc`. I agree that this might be something we want to fix though. The key is that environment variable settings are stronger than `Prusti.toml` ones (see [here](https://viperproject.github.io/prusti-dev/dev-guide/config/providing.html)). In `prusti-rustc` the `CACHE_PATH` setting doesn't have a nice default, but in `cargo-prusti` it does - thus we disable it by default in `prusti-rustc` but do set it through the environment variable when running it in `cargo-prusti`. But the `Prusti.toml` file is only loaded once in `prusti-rustc` and at that point it has no effect since the environment variable is set. This is also an issue with the other settings set by `cargo-prusti`, namely `PRUSTI_QUIET`, `PRUSTI_FULL_COMPILATION` and `PRUSTI_LOG_DIR` - none of these can be changed with a `Prusti.toml` file when using `cargo-prusti`.
One way to fix this would be to duplicate the load-`Prusti.toml`-settings code into `cargo-prusti` and at that point check if the setting is present, though this might get ugly. Another, would be to introduce a different method for `cargo-prusti` to communicate with `prusti-rustc` and the latter decides which settings to actually use - makes the settings code of `prusti-rustc` more ugly.

**Comment by fpoli** [comment]
@JonasAlaif What about removing this (unused) feature...
https://github.com/viperproject/prusti-dev/blob/f8e70f9037b964498e83f58a3bb9387f60c7a454/prusti-common/src/config.rs#L130-L136

...adding the following *before* loading "Prusti.toml" (a few lines above)?
```rust
        // Override with env variables (`DEFAULT_PRUSTI_CACHE_PATH`, ...)
        settings.merge(
            Environment::with_prefix("DEFAULT_PRUSTI").ignore_empty(true)
        ).unwrap();
        check_keys(&settings, &allowed_keys, "environment variables");
```

This way, `cargo-prusti` can set `DEFAULT_PRUSTI_CACHE_PATH` without even checking if `PRUSTI_CACHE_PATH` is set or not.

**Comment by vakaras** [comment]
I guess the easiest would be to make the `prusti-rustc` settings to use the value stored at `DEFAULT_PRUSTI_CACHE_PATH` as the default value for the cache path, which can be overridden by any method. Then, `cargo-prusti` would set `DEFAULT_PRUSTI_CACHE_PATH` to `target/...`

**Comment by fpoli** [comment]
Wow, we collided even on the name of the environment variable. Amazing :rofl:

**Comment by JonasAlaif** [comment]
Hmm I wonder if `PRUSTI_CONFIG` will ever have a use case? My alternative suggestion, to preserve it, would be to sell it as defaulting to `PRUSTI_CONFIG=./Prusti.toml` and merge in this option of "Prusti.toml". That way, we keep things "simple" with still 4 ways to provide flags

**Comment by fpoli** [comment]
> Hmm I wonder if `PRUSTI_CONFIG` will ever have a use case? My alternative suggestion, to preserve it, would be to sell it as defaulting to `PRUSTI_CONFIG=./Prusti.toml` and merge in this option of "Prusti.toml". That way, we keep things "simple" with still 4 ways to provide flags

That sounds good to me!
