### ISSUE TITLE
Any way to debug as a user?

### ISSUE THREAD

**Issue by ghost** [viperproject/prusti-dev#908]
I'm trying to verify the following without success.

```
#![feature(box_patterns)]
#![allow(dead_code)]
#![allow(unused_variables)]

use prusti_contracts::*;

pub type Term = u64;

pub enum Message {
    AppendEntries {
        term: Term
    },
}

impl Message{
    #[pure]
    pub fn term(&self) -> Term {
        match self {
            Message::AppendEntries{term} => *term
        }
    }
}

pub struct Raft {
    pub current_term: Term,
}

impl Raft {

    #[ensures(result.current_term == 0)]
    pub fn new() -> Self {
        Self {
            current_term: 0,
        }
    }
    
    pub fn handle_message(&mut self, msg: &Message){
        match msg {
            Message::AppendEntries { term } => self.handle_append_entries(msg)
        };
    }

    #[requires(matches!(msg, Message::AppendEntries{ term }))]
    #[ensures(msg.term() < self.current_term ==> self.current_term == old(self.current_term))]
    fn handle_append_entries(&mut self, msg: &Message){
        if msg.term() >= self.current_term {
            self.current_term = msg.term()+1;
        }
    }
}

fn main(){}
```

The postcondition `#[ensures(msg.term() < self.current_term ==> self.current_term == old(self.current_term))]` fails to be proven. Is there any way I can debug this to understand why it fails?

**Comment by fpoli** [comment]
The standard way (like in most deductive verification tools) is to add to the code small assertions that should imply the postcondition, e.g. adding ` else { assert!(self.current_term == old_current_term) }` after the `if` and `let old_current_term = self.current_term` at the beginning of the method, in order to find out which assertion fails. Another way is to ask Prusti to generate counterexamples (`PRUSTI_COUNTEREXAMPLE=true` environment variable, or `-Pcounterexample=true` flag). However, counterexamples are still experimental.

(Trying your code, I get "[E0609] no field `current_term` on type `&Message`." at the postcondition of `term`. Maybe there is a copy-paste error?)

**Comment by ghost** [comment]
> The standard way (like in most deductive verification tools) is to add to the code small assertions that should imply the postcondition, e.g. adding ` else { assert!(self.current_term == old_current_term) }` after the `if` and `let old_current_term = self.current_term` at the beginning of the method, in order to find out which assertion fails. Another way is to ask Prusti to generate counterexamples (`PRUSTI_COUNTEREXAMPLE=true` environment variable, or `-Pcounterexample=true` flag). However, counterexamples are still experimental.
> 
Great, I will try it.

> (Trying your code, I get "[E0609] no field `current_term` on type `&Message`." at the postcondition of `term`. Maybe there is a copy-paste error?)

Yes, sorry for that. I updated the snippet.

**Comment by fpoli** [comment]
> Yes, sorry for that. I updated the snippet.

Thanks! Weird that it doesn't verify. To me, it looks like a Prusti bug.

**Comment by JonasAlaif** [comment]
This isn't a bug. The correct postcondition is:
```
#[ensures(msg.term() < old(self.current_term) ==> self.current_term == old(self.current_term))]
```
Note the `old(...)` in `msg.term() < old(self.current_term)`
