### ISSUE TITLE
Prusti unexpected internal error

### ISSUE THREAD

**Issue by Omar0Tarek** [viperproject/prusti-dev#960]
Verifying the following Rust code with Prusti produces an unexpected internal error.

The code is:

```rust
use prusti_contracts::*;

#[requires(array.len() >= 1)]
fn foo(array : &mut [i32]) {
    let mut end = array.len();
    while end > 0 {
        body_invariant!(end >= 1 && end <= array.len());
        let mut start = end - 1;
        while start > 0 {
            body_invariant!(start >= 1);
            start -= 1;
            bar(&mut array[start..end]);
        }
        end -= 1;
    }
}

fn bar(v : &mut [i32]) {}

fn main() {}
```

The error is:
```
- [Prusti internal error] Prusti encountered an unexpected internal error
- This could be caused by too small assertion timeout. Try increasing it by setting the configuration parameter ASSERT_TIMEOUT to a larger value.
- We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new
Details: unregistered verification error: [application.precondition:assertion.false; 0] Precondition of function lookup_pure__$TY$__Slice$i32$i32$ might not hold. Assertion j < Slice$len__$TY$__i32$(_LET_1) might not hold. (@0.0)
```

The code should fail the verification anyways, as there is a missing body invariant, and the verification succeeds after adding it.

The correct code - after adding the missing invariant in the inner while loop - is:

```rust
use prusti_contracts::*;

#[requires(array.len() >= 1)]
fn foo(array : &mut [i32]) {
    let mut end = array.len();
    while end > 0 {
        body_invariant!(end >= 1 && end <= array.len());
        let mut start = end - 1;
        while start > 0 {
            body_invariant!(start >= 1 && end <= array.len()); // added body invariant
            start -= 1;
            bar(&mut array[start..end]);
        }
        end -= 1;
    }
}

fn bar(v : &mut [i32]) {}

fn main() {}
```

**Comment by vakaras** [comment]
The problem seems to be that [in this line](https://github.com/viperproject/prusti-dev/blob/854133f83c2d1975baa1a7a563f936139e8542c9/prusti-viper/src/encoder/array_encoder.rs#L67) a default position is used. @JonasAlaif

**Comment by JonasAlaif** [comment]
A few points:

- The code you give does not actually fail as reported on the latest master, likely due to the changes in https://github.com/viperproject/prusti-dev/pull/895. The error now is:
```
error: [Prusti: verification error] loop invariant might not hold after a loop iteration that preserves the loop condition.
 --> ./prusti-tests/tests/verify/pass/issues/issue960.rs:7:37
  |
7 |         body_invariant!(end >= 1 && end <= array.len());
  |                                     ^^^^^^^^^^^^^^^^^^
  |
```
- The current issue is that `<[i32] as std::ops::IndexMut<std::ops::Range<usize>>>::index_mut` is not handled by a special case, but rather as a generic function call. Since the argument to this is a mutable reference to the slice, the slice information is havocd (including the length, thus leading to the `end <= array.len()` failure).

Ideally we would fix this by adding a spec to all of these `index`, `index_mut`, ... stdlib functions with `extern_spec` and importing that with `prusti_contracts`. I'm not sure if `extern_spec` works well enough for that yet @Aurel300? But furthermore I'm not sure how we would handle importing contracts. If this needs to be fixed ASAP, one could look at implementing `index_mut` (maybe similarly to how `index` is implemented?).

**Comment by JonasAlaif** [comment]
The issue you report does come up, but in an example where indexing is supported:
```rust
use prusti_contracts::*;

fn foo(slice : &[i32]) {
    let subslice = &slice[0..10];
}

fn main() {}
```
I'll take a look at this

**Comment by JonasAlaif** [comment]
Oops sorry for the previous comments. There are two issues here, both to do with `encode_sequence_index_call`:

1. That it is used for `<[i32] as std::ops::IndexMut<std::ops::Range<usize>>>::index_mut` in general. I think that such a mutable borrow will need a different contract (e.g. to update the fields of the original slice/array when it expires).
2. That it doesn't check the range indices to be in bounds (this check is performed in the end by the `lookup` function). This can easily be fixed by adding the correct checks in this function.

Thanks for the report! As a side note, the correct invariant is not `body_invariant!(start >= 1 && end <= array.len());` but instead `body_invariant!(start >= 1 && start <= end);` (`end` isn't updated in the inner loop so we don't forget anything about it)
